
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
development:
  <<: *default
  database: blogapp_development

  
test:
  <<: *default
  database: blogapp_test


production:
  <<: *default
  database: blogapp_production
  username: blogapp
  password: <%= ENV['BLOGAPP_DATABASE_PASSWORD'] %>
